[package]
name = "age"
version.workspace = true
edition.workspace = true

[dependencies]
bitflags.workspace = true
pollster.workspace = true
raw-window-handle.workspace = true
wgpu.workspace = true
winit.workspace = true
