[package]
name = "age"
version.workspace = true
edition.workspace = true

[dependencies]
age_math.workspace = true

bytemuck.workspace = true
fontdue.workspace = true
image.workspace = true
pollster.workspace = true
wgpu.workspace = true
winit.workspace = true

glam = "*"
